version: "3.9"
services:
  mysql:
    image: mysql:8.0
    container_name: stations-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: .
    container_name: stations-service
    restart: always
    ports:
      - "${PORT}:3000"
    environment:
      DB_HOST: mysql      
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      PORT: ${PORT}
    depends_on:
      - mysql

volumes:
  mysql_data:
